version: "3"

services:
  web:
    image: sonarqube:7.1-alpine
    ports:
      - "80:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=Standar123.
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=Standar123.
      
  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    links:
      - postgres:db
    depends_on:
      - db
